
- name: Summarise
  task_type: gemini_summarise
  description: Short abstract
  parameters:
    model: gemini-pro
    summary_length: short
  output_config:
    overwrite: false
    filename_suffix: "_summary"

- name: Transform
  task_type: gemini_transform
  description: Uppercase transform
  parameters:
    model: gemini-pro
    prompt_template: "Please convert the text to uppercase:\n"
  output_config:
    overwrite: false
